2014-11-28 23:27:16.063 5695 INFO neutron.common.config [-] Logging enabled!
2014-11-28 23:27:17.204 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.228 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.255 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.276 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.299 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.320 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.358 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.376 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.385 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.398 5695 INFO oslo.messaging._drivers.impl_rabbit [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.420 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.431 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.436 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.451 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:27:17.504 5695 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 None] Mapping physical network physnet-tenant to bridge br-tenant
2014-11-28 23:27:18.649 5695 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 None] Agent initialized successfully, now running... 
2014-11-28 23:27:18.654 5695 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 None] Agent out of sync with plugin!
2014-11-28 23:33:50.941 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: Socket closed
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 735, in _consume
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=timeout)
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 281, in drain_events
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 94, in drain_events
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 299, in drain_events
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 362, in _wait_multiple
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 326, in read_timeout
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2014-11-28 23:33:50.941 5695 TRACE oslo.messaging._drivers.impl_rabbit 
2014-11-28 23:33:50.943 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-28 23:33:50.943 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: Socket closed
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 735, in _consume
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=timeout)
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 281, in drain_events
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 94, in drain_events
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 299, in drain_events
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 362, in _wait_multiple
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 326, in read_timeout
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2014-11-28 23:33:50.943 5695 TRACE oslo.messaging._drivers.impl_rabbit 
2014-11-28 23:33:50.944 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-28 23:33:50.944 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: Socket closed
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 735, in _consume
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=timeout)
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 281, in drain_events
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 94, in drain_events
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 299, in drain_events
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 362, in _wait_multiple
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 326, in read_timeout
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2014-11-28 23:33:50.944 5695 TRACE oslo.messaging._drivers.impl_rabbit 
2014-11-28 23:33:50.945 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-28 23:33:50.945 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: Socket closed
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 735, in _consume
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=timeout)
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 281, in drain_events
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 94, in drain_events
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 299, in drain_events
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 362, in _wait_multiple
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 326, in read_timeout
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2014-11-28 23:33:50.945 5695 TRACE oslo.messaging._drivers.impl_rabbit 
2014-11-28 23:33:50.946 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-28 23:33:50.947 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: Socket closed
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 655, in ensure
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 735, in _consume
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=timeout)
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 281, in drain_events
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 94, in drain_events
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 299, in drain_events
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 362, in _wait_multiple
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 326, in read_timeout
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2014-11-28 23:33:50.947 5695 TRACE oslo.messaging._drivers.impl_rabbit 
2014-11-28 23:33:50.947 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2014-11-28 23:33:51.949 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:33:51.981 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:33:52.054 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:33:52.075 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:33:52.088 5695 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:33:56.982 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.0.1.111:5672 is unreachable: timed out. Trying again in 1 seconds.
2014-11-28 23:33:57.013 5695 ERROR neutron.agent.linux.utils [req-a8e473b6-a66c-4f7e-8a2e-e61188cc52d7 None] 
Command: ['ps', '--ppid', '5839', '-o', 'pid=']
Exit code: 1
Stdout: ''
Stderr: ''
2014-11-28 23:33:57.061 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.0.1.111:5672 is unreachable: timed out. Trying again in 1 seconds.
2014-11-28 23:33:57.079 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.0.1.111:5672 is unreachable: timed out. Trying again in 1 seconds.
2014-11-28 23:33:57.091 5695 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.0.1.111:5672 is unreachable: timed out. Trying again in 1 seconds.
2014-11-28 23:38:03.222 2180 INFO neutron.common.config [-] Logging enabled!
2014-11-28 23:38:04.380 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:04.419 2180 ERROR oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] AMQP server on 10.0.1.111:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.
2014-11-28 23:38:05.421 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Delaying reconnect for 1.0 seconds...
2014-11-28 23:38:06.422 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:06.436 2180 ERROR oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] AMQP server on 10.0.1.111:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 3 seconds.
2014-11-28 23:38:09.437 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Delaying reconnect for 1.0 seconds...
2014-11-28 23:38:10.439 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:10.453 2180 ERROR oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] AMQP server on 10.0.1.111:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 5 seconds.
2014-11-28 23:38:15.456 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Delaying reconnect for 1.0 seconds...
2014-11-28 23:38:16.458 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.476 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.490 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.505 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.515 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.526 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.535 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.547 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.555 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.567 2180 INFO oslo.messaging._drivers.impl_rabbit [req-42891396-ed46-455c-ba03-f59abf7a7599 ] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.582 2180 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.594 2180 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.598 2180 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.613 2180 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.0.1.111:5672
2014-11-28 23:38:16.653 2180 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-42891396-ed46-455c-ba03-f59abf7a7599 None] Mapping physical network physnet-tenant to bridge br-tenant
2014-11-28 23:38:17.533 2180 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-42891396-ed46-455c-ba03-f59abf7a7599 None] Agent initialized successfully, now running... 
2014-11-28 23:38:17.537 2180 INFO neutron.plugins.openvswitch.agent.ovs_neutron_agent [req-42891396-ed46-455c-ba03-f59abf7a7599 None] Agent out of sync with plugin!
2014-11-28 23:39:16.618 2180 ERROR neutron.plugins.openvswitch.agent.ovs_neutron_agent [-] Failed reporting state!
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent Traceback (most recent call last):
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/plugins/openvswitch/agent/ovs_neutron_agent.py", line 259, in _report_state
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     self.use_call)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 70, in report_state
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     return self.call(context, msg)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/common/log.py", line 34, in wrapper
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     return method(*args, **kwargs)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 161, in call
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     context, msg, rpc_method='call', **kwargs)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 187, in __call_rpc_method
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     return func(context, msg['method'], **msg['args'])
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 389, in call
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     return self.prepare().call(ctxt, method, **kwargs)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 152, in call
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     retry=self.retry)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/transport.py", line 90, in _send
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     timeout=timeout, retry=retry)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 408, in send
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     retry=retry)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 397, in _send
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     result = self._waiter.wait(msg_id, timeout)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 285, in wait
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     reply, ending = self._poll_connection(msg_id, timeout)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 235, in _poll_connection
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent     % msg_id)
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent MessagingTimeout: Timed out waiting for a reply to message ID 621572fcc3d44cc4b97812efedd119bc
2014-11-28 23:39:16.618 2180 TRACE neutron.plugins.openvswitch.agent.ovs_neutron_agent 
2014-11-28 23:39:16.621 2180 WARNING neutron.openstack.common.loopingcall [-] task run outlasted interval by 30.040129 sec
